# Generated by Django 5.1.6 on 2025-02-26 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('exam_type', models.CharField(choices=[('practice', "Exercice d'entraînement"), ('mock', 'Examen blanc'), ('past_year', 'Examen session antérieure')], default='practice', max_length=50)),
                ('time_limit', models.IntegerField(blank=True, help_text='Temps limite en minutes', null=True)),
                ('passing_score', models.IntegerField(default=50, help_text='Score en pourcentage pour réussir')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('order', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_exercises', to='exams.exam')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_links', to='content.exercise')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('exam', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exercises',
            field=models.ManyToManyField(through='exams.ExamExercise', to='content.exercise'),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('completion_time', models.IntegerField(help_text='Temps de réalisation en minutes')),
                ('passed', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exam', 'attempt_number')},
            },
        ),
    ]
